import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import ReduxWrapper from '../provider/redux/ReduxWrapper';

import Nav from './../components/Nav';

import './styles/globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Prisma Next.js Example',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body className={inter.className}>
          {' '}
          <Nav />
          {children}
        </body>
      </html>
    </ReduxWrapper>
  );
}
