import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import ReduxWrapper from '../provider/redux/ReduxWrapper';

import './styles/globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'S Kociuba - Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ReduxWrapper>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReduxWrapper>
  );
}
